In [1]:
import pandas as pd
from torch.serialization import location_tag

In [3]:
books = pd.read_csv('books_cleaned.csv')

In [6]:
books['categories'].value_counts().reset_index().sort_values('count', ascending=False)

                     categories  count
0                       Fiction   2111
1              Juvenile Fiction    390
2     Biography & Autobiography    311
3                       History    207
4            Literary Criticism    124
..                          ...    ...
474                  Aged women      1
475                 Imperialism      1
476  Human-animal relationships      1
477                       Amish      1
478               Human cloning      1

[479 rows x 2 columns]

As both (few) and too many categories are not recommended, we need to regroup the categories reasonable, say, `fiction` and `non-fiction`.

In [7]:
category_mapping = {
                    'Fiction' : "Fiction",
                    'Juvenile Fiction': "Children's Fiction",
                    'Biography & Autobiography': "Nonfiction",
                    'History': "Nonfiction",
                    'Literary Criticism': "Nonfiction",
                    'Philosophy': "Nonfiction",
                    'Religion': "Nonfiction",
                    'Comics & Graphic Novels': "Fiction",
                    'Drama': "Fiction",
                    'Juvenile Nonfiction': "Children's Nonfiction",
                    'Science': "Nonfiction",
                    'Poetry': "Fiction"
                    }
books['new_categories'] = books['categories'].map(category_mapping)
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,new_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,NaN
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,NaN
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,NaN
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...,NaN
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,NaN
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction

In [8]:
books[books['new_categories'].notna()]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,new_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
8,9780006482079,0006482074,Warhost of Vastmark,Janny Wurts,Fiction,http://books.google.com/books/content?id=uOL0f...,"Tricked once more by his wily half-brother, Ly...",1995.0,4.03,522.0,2966.0,Warhost of Vastmark,9780006482079 Tricked once more by his wily ha...,Fiction
30,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,Ocean Star Express,9780006646006 Joe and his parents are enjoying...,Children's Fiction
46,9780007121014,0007121016,Taken at the Flood,Agatha Christie,Fiction,http://books.google.com/books/content?id=3gWlx...,A Few Weeks After Marrying An Attractive Young...,2002.0,3.71,352.0,8852.0,Taken at the Flood,9780007121014 A Few Weeks After Marrying An At...,Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5178,9781933648279,1933648279,Night Has a Thousand Eyes,Cornell Woolrich,Fiction,http://books.google.com/books/content?id=3Gk6s...,"""Cornell Woolrich's novels define the essence ...",2007.0,3.77,344.0,680.0,Night Has a Thousand Eyes,"9781933648279 ""Cornell Woolrich's novels defin...",Fiction
5188,9784770028969,4770028962,Coin Locker Babies,村上龍,Fiction,http://books.google.com/books/content?id=87DJw...,Rescued from the lockers in which they were le...,2002.0,3.75,393.0,5560.0,Coin Locker Babies,9784770028969 Rescued from the lockers in whic...,Fiction
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,"Cry, the Peacock",9788122200850 This book is the story of a youn...,Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction

## Zero-shot classification from Hugging Face

Zero-Shot Classification (ZSC) is a machine learning technique that enables models to classify data into categories they have never encountered during training. Unlike traditional supervised learning, which requires labeled examples for every class, ZSC leverages prior knowledge to generalize to unseen classes. This is particularly useful in scenarios where collecting labeled data for every possible category is impractical or impossible.

#### How It Works

Zero-shot classification relies on semantic knowledge transfer to bridge the gap between seen and unseen classes. This is achieved using techniques such as word embeddings (e.g., `Word2Vec`, `GloVe`), pre-trained language models (e.g., `BERT`, `GPT`, `CLIP`), or knowledge graphs. The model maps both input data and class descriptions into a shared embedding space and uses similarity measures (e.g., `cosine` similarity) to determine the most relevant class.

For example, if a model trained on "cats" and "dogs" is asked to classify a "lion," it can infer that a lion is semantically similar to a cat and make the correct classification.

#### Key Components

1. **Semantic Embeddings:** Classes and input data are represented as vector embeddings that capture their meaning.

2. **Similarity Matching:** The model compares the input's embedding with class embeddings and selects the class with the highest similarity score.

In [11]:
from transformers import pipeline
# Initialize the zero-shot classification pipeline
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli", device="cpu")

candidate_labels = ["Fiction", "Nonfiction"]

Device set to use cpu

In [14]:
# Perform classification
description_seq = books.loc[books['new_categories']=="Fiction", "description"].iloc[0]

result = classifier(description_seq, candidate_labels)

Classification Results:
Fiction: 0.8438
Nonfiction: 0.1562

In [27]:
import numpy as np
def category_predictor(text_sequence: str, proposed_catagories: list[str]):
    """ Obtain the predicted probability of each category. Pick the category with the highest probability. """
    result = classifier(text_sequence, proposed_catagories)
    idx = np.argmax(result['scores'])
    predicted_label = result['labels'][idx]
    return predicted_label

# Evaluate this model

First we take a sample of 300 books from each group.

Next, we make a prediction of categories for each book description.

Lastly, we compare the actual groups with predicted ones, and thus evaluate the model's ability to generalize making categories, so that we use it to predict the nan ones in the 'new_category' column.

In [30]:
fiction_sample = books[books['new_categories'] == 'Fiction'].sample(300, random_state=42)
nonfiction_sample = books[books['new_categories'] == 'Nonfiction'].sample(300, random_state=42)

result_df = pd.concat([fiction_sample, nonfiction_sample], ignore_index=True)

In [36]:
actual_categories = []
predicted_categories = []
for _, row in result.iterrows():
    predicted_label = category_predictor(row['description'], candidate_labels)
    actual_categories.append(row['new_categories'])
    predicted_categories.append(predicted_label)

In [38]:
from sklearn.metrics import classification_report
print(classification_report(actual_categories, predicted_categories))

              precision    recall  f1-score   support

     Fiction       0.85      0.64      0.73       300
  Nonfiction       0.71      0.88      0.79       300

    accuracy                           0.76       600
   macro avg       0.78      0.76      0.76       600
weighted avg       0.78      0.76      0.76       600

In [41]:
from tqdm import tqdm
missing_cats = books.loc[books['new_categories'].isna(), ['isbn13', 'description']]
PRED_CATS = []
for _, row in tqdm(missing_cats.iterrows(), total=len(missing_cats)):
    predicted_label = category_predictor(row['description'], candidate_labels)
    data = {
        'isbn13': row['isbn13'],
        'new_categories': predicted_label
    }
    PRED_CATS.append(data)

100%|██████████| 1454/1454 [29:16<00:00,  1.21s/it]

In [51]:
predicted_cats_df = pd.DataFrame(PRED_CATS).rename(columns={'new_categories': 'pred_new_categories'})
predicted_cats_df

             isbn13 pred_new_categories
0     9780002261982             Fiction
1     9780006280897          Nonfiction
2     9780006280934          Nonfiction
3     9780006380832          Nonfiction
4     9780006470229             Fiction
...             ...                 ...
1449  9788125026600          Nonfiction
1450  9788171565641             Fiction
1451  9788172235222             Fiction
1452  9788173031014          Nonfiction
1453  9788179921623             Fiction

[1454 rows x 2 columns]

In [52]:
books_df = pd.merge(books, predicted_cats_df, on='isbn13', how='left')
books_df['new_categories'] = np.where(books_df['new_categories'].isna(),books_df['pred_new_categories'], books_df['new_categories'])
books_final = books_df.drop(columns="pred_new_categories").copy()
books_final

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,new_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...,Nonfiction
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...,Fiction
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...,Nonfiction
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction

In [55]:
books_final.to_csv("books_predicted_categories.csv", index=False)

Of course it is pragmatic to further classify descriptions to have a little more options (especially split the fiction types as they cover ~55%). However, we do not have many books under each category of the categories. So, we can not validate the predictions doe to insufficient data for each group. Thus, for now, the two classifications are enough.

Our next step will be **sentiment analysis.** We need to detect emotions. We use **LLMs** to classify texts to **7 categories of emotions.** This task is given at `03_sentiment_analysis.ipynb`.

<img src="img_1.png"></img>